name: Deploy to GCP Cloud Run

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1: Authenticate to Google Cloud using the service account key stored in secrets
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Step 2: Set up Google Cloud SDK
      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Step 3: Configure Docker authentication for Artifact Registry (europe-west3 region)
      - name: Configure Docker
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev

      # Step 4: Build Docker image with the Artifact Registry repo path
      - name: Build Docker image
        run: |
          docker build -t europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/eurex-risk-monitor:${{ github.sha }} .

      # Step 5: Push Docker image to Artifact Registry
      - name: Push Docker image to Artifact Registry
        run: |
          docker push europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/eurex-risk-monitor:${{ github.sha }}

      # Step 6: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy eurex-risk-monitor \
            --image europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/eurex-risk-monitor:${{ github.sha }} \
            --platform managed \
            --region europe-west3 \
            --allow-unauthenticated \
            --quiet \
            --set-env-vars PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},DATASET_ID=${{ secrets.DATASET_ID }},TABLE_ID=${{ secrets.TABLE_ID }}
